require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'AppgainTask' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-appgain-sdk', :path => '../node_modules/react-native-appgain-sdk-library'

  target 'AppgainTaskTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

end

target 'AppgainTask-tvOS' do
  # Pods for AppgainTask-tvOS

  target 'AppgainTask-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
